language: node_js
notifications:
  email: true
node_js: 12
jobs:
  include:
  - stage: test
    script:
    - npm run build
    - npm run test
  # - stage: deploy
  #   if: branch = main
  #   script: npm run deploy
notifications:
  email:
    on_failure: always